sonar.projectKey=url-shortener-api
sonar.projectName=url-shortener-api

sonar.sources=url-shortener-api/src,database/cassandra,deploy/helm/url-shortener/templates,url-shortener-api/Dockerfile
sonar.tests=url-shortener-api/tests
sonar.test.inclusions=url-shortener-api/tests/**/*.rs
sonar.exclusions=**/target/**
sonar.rust.lcov.reportPaths=url-shortener-api/target/rust-coverage.lcov
sonar.rust.cargo.manifestPaths=url-shortener-api/Cargo.toml
sonar.rust.clippy.enabled=false
sonar.rust.clippyReport.reportPaths=url-shortener-api/target/clippy-report.json
