sonar.projectKey=url-shortener-frontend
sonar.projectName=url-shortener-frontend

sonar.sources=url-shortener-frontend/src
sonar.tests=url-shortener-frontend/tests/unit,url-shortener-frontend/e2e
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.spec.tsx,**/*.test.tsx,**/e2e/**/*.ts
sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/test-results/**,**/playwright-report/**
sonar.javascript.lcov.reportPaths=url-shortener-frontend/coverage/lcov.info
